name: Count Lines of Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count lines of code
        run: cloc --by-file --sum-one --json .
